In [14]:
import numpy as np
import pandas as pd

In [15]:
data = pd.read_csv(r'mydata_cleaned.csv', encoding='unicode_escape')

In [24]:
data

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
...,...,...,...,...,...,...,...,...,...
820,Biomutant,2019.0,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
821,de Blob,2017.0,Platform,THQ Nordic,0.00,0.00,0.00,0.00,0.00
822,Chaos on Deponia,2017.0,Adventure,Daedalic Entertainment,0.00,0.00,0.00,0.00,0.00
823,Code Vein,2018.0,Action,Bandai Namco Entertainment,0.00,0.00,0.00,0.00,0.00
824,Radial G Racing Revolved,2017.0,Racing,Tammeka Games,0.00,0.00,0.00,0.00,0.00

In [31]:
#nan_mask = data['Year'].isna()                            bu asamalar datayi temizleyip acma asamalari
#data_cleaned = data[~nan_mask]                            yukarda cagirilan data normalde orjinal data 
#data_cleaned.to_csv('mydata_cleaned.csv', index=False)    ben temizledikten sonra tekra ayni yerde bu datay cagirdim
data

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
...,...,...,...,...,...,...,...,...,...
820,Biomutant,2019.0,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
821,de Blob,2017.0,Platform,THQ Nordic,0.00,0.00,0.00,0.00,0.00
822,Chaos on Deponia,2017.0,Adventure,Daedalic Entertainment,0.00,0.00,0.00,0.00,0.00
823,Code Vein,2018.0,Action,Bandai Namco Entertainment,0.00,0.00,0.00,0.00,0.00
824,Radial G Racing Revolved,2017.0,Racing,Tammeka Games,0.00,0.00,0.00,0.00,0.00

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Game           825 non-null    object
 1   Year           825 non-null    float64
 2   Genre          825 non-null    object
 3   Publisher      825 non-null    object
 4   North America  825 non-null    float64
 5   Europe         825 non-null    float64
 6   Japan          825 non-null    float64
 7   Rest of World  825 non-null    float64
 8   Global         825 non-null    float64
dtypes: float64(6), object(3)
memory usage: 58.1+ KB

In [33]:
data.dtypes

Game              object
Year             float64
Genre             object
Publisher         object
North America    float64
Europe           float64
Japan            float64
Rest of World    float64
Global           float64
dtype: object

In [34]:
data['Year'] = data["Year"].astype(int)

In [36]:
data.dtypes

Game              object
Year               int32
Genre             object
Publisher         object
North America    float64
Europe           float64
Japan            float64
Rest of World    float64
Global           float64
dtype: object

In [37]:
data

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
...,...,...,...,...,...,...,...,...,...
820,Biomutant,2019,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
821,de Blob,2017,Platform,THQ Nordic,0.00,0.00,0.00,0.00,0.00
822,Chaos on Deponia,2017,Adventure,Daedalic Entertainment,0.00,0.00,0.00,0.00,0.00
823,Code Vein,2018,Action,Bandai Namco Entertainment,0.00,0.00,0.00,0.00,0.00
824,Radial G Racing Revolved,2017,Racing,Tammeka Games,0.00,0.00,0.00,0.00,0.00

In [38]:
data.Global.value_counts()          #burdan son 116 satirin 0 oldugnunu anliyoruz ve onlari data setinden cikartiyoruz

0.00    116
0.02     39
0.04     39
0.03     37
0.01     34
       ...
2.06      1
2.05      1
2.02      1
1.98      1
1.21      1
Name: Global, Length: 206, dtype: int64

In [39]:
data = data[data["Global"] != 0]
data

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
...,...,...,...,...,...,...,...,...,...
704,Hyper Light Drifter,2017,Role-Playing,Active Gaming Media,0.00,0.00,0.01,0.00,0.01
705,Teslagrad,2014,Platform,Rain Games,0.00,0.01,0.00,0.00,0.01
706,Darius Burst: Chronicle Saviours,2017,Action,Kadokawa Games,0.00,0.00,0.01,0.00,0.01
707,The Escapists: The Walking Dead,2016,Action,Team17 Software,0.00,0.00,0.00,0.00,0.01
708,Super Meat Boy,2016,Platform,Team Meat,0.00,0.00,0.00,0.00,0.01

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 709 entries, 0 to 708
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Game           709 non-null    object
 1   Year           709 non-null    int32
 2   Genre          709 non-null    object
 3   Publisher      709 non-null    object
 4   North America  709 non-null    float64
 5   Europe         709 non-null    float64
 6   Japan          709 non-null    float64
 7   Rest of World  709 non-null    float64
 8   Global         709 non-null    float64
dtypes: float64(5), int32(1), object(3)
memory usage: 52.6+ KB

In [41]:
data.describe()

,Year,North America,Europe,Japan,Rest of World,Global
count,709.000000,709.000000,709.000000,709.000000,709.000000,709.000000
mean,2015.953456,0.298406,0.362581,0.048928,0.129803,0.839803
std,1.172582,0.659710,0.926771,0.127947,0.292334,1.853915
min,2013.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,2015.000000,0.020000,0.000000,0.000000,0.010000,0.060000
50%,2016.000000,0.070000,0.050000,0.010000,0.030000,0.170000
75%,2017.000000,0.240000,0.310000,0.050000,0.110000,0.720000
max,2018.000000,6.180000,9.710000,2.170000,3.020000,19.390000